---
title: "initial_analysis"
output: html_document
date: "2025-02-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning = FALSE}
library("immunarch")
```

# load data
All Samples (H+OC) TRA and TRB 
```{r}
# alpha chain
immdataA<-repLoad("/home/ubuntu/CRC/CRC_raw_data/IP_outputs_TRA/IP_outputs")

# beta chain
immdataB<-repLoad("/home/ubuntu/CRC/CRC_raw_data/IP_outputs_TRB/IP_outputs")
```

# alpha stats
```{r}
# clone count
countA <- repExplore(immdataA$data, .method = "clones", .col = "aa", .coding = TRUE)
sum(countA$Clones)
```

```{r}
# mean clones per sample
mean(countA$Clones)
```

```{r}
# clonotypes count
uniqueA <- repExplore(immdataA$data, .method = "volume", .col = "aa", .coding = TRUE)
```

```{r}
# mean clonotypes per sample
mean(uniqueA$Volume)
```

# beta stats
```{r}
# clone count
countB <- repExplore(immdataB$data, .method = "clones", .col = "aa", .coding = TRUE)
sum(countB$Clones)
```

```{r}
# mean clones per sample
mean(countB$Clones)
```

```{r}
# clonotypes count
uniqueB <- repExplore(immdataB$data, .method = "volume", .col = "aa", .coding = TRUE)
```

```{r}
# mean clonotypes per sample
mean(uniqueB$Volume)
```